// client/src/utils/latexExport.ts

export const generateLatex = (
  layout: any[], 
  generatedQuestions: any[], 
  title: string = "Exam Draft",
  imageMap?: Map<string, string> // Map for local zip paths
): string => {
  let tex = `\\documentclass[11pt, addpoints]{exam}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath}
\\usepackage{graphicx}
\\usepackage{enumitem}
\\usepackage{geometry}
\\usepackage{pgfplots} % Native line/scatter/bar charts
\\pgfplotsset{compat=1.18}
\\geometry{a4paper, margin=1in}

% --- IB Style Exam Formatting ---
\\pointsinrightmargin
\\bracketedpoints
\\marginpointname{} % Removes the word "points" next to the number
\\renewcommand{\\choicelabel}{\\Alph*.} % The asterisk is required for A, B, C, D labels

% --- Custom Header & Footer ---
\\pagestyle{headandfoot}
\\firstpageheader{}{}{}
\\runningheader{Physics}{Higher level}{Paper 1A \\& 2}
\\firstpagefooter{}{\\thepage}{}
\\runningfooter{}{\\thepage}{Turn over}

\\begin{document}

% --- IB Style Cover Page ---
\\begin{titlepage}
    \\begin{flushleft}
    \\vspace*{1cm}
    {\\huge \\textbf{Physics}} \\\\[0.3cm]
    {\\Large \\textbf{Higher level}} \\\\[0.2cm]
    {\\Large \\textbf{${cleanTextForLatex(title)}}} \\\\[1cm]
    
    {\\large \\textbf{Time allowed: 2 hours}} \\\\[1.5cm]
    
    {\\Large \\textbf{Instructions to candidates}} \\\\[0.5cm]
    
    \\normalsize
    \\begin{itemize}[label=$\\bullet$, itemsep=0.3cm]
        \\item Do not open this examination paper until instructed to do so.
        \\item Answer all questions.
        \\item Answers for structured questions must be written within the answer boxes provided.
        \\item A calculator is required for this paper.
        \\item A clean copy of the physics data booklet is required for this paper.
    \\end{itemize}
    
    \\vfill
    \\rule{\\textwidth}{0.4pt} \\\\
    \\vspace{0.2cm}
    \\textit{\\small \\copyright \\ Generated by Test Agent }
    \\end{flushleft}
\\end{titlepage}

\\begin{questions}\n\n`;

  layout.forEach((item) => {
    if (item.itemType === 'BlankPage') {
      tex += `\\newpage\n\\thispagestyle{empty}\n\\mbox{}\n\\newpage\n\n`;
      return;
    }

    if (item.itemType === 'StaticAsset') {
      tex += `% [STATIC ASSET PLACEHOLDER: ${item.title}]\n\n`;
      return;
    }

    if (item.itemType === 'Question') {
      const q = generatedQuestions.find(gq => gq._id === item.itemId);
      if (!q) return;

      const renderAssets = (assets: any[]) => {
        let assetTex = '';
        if (assets && assets.length > 0) {
          assets.forEach((asset: any) => {
            if (asset.type === 'image') {
               const localPath = (imageMap && asset.image_data) ? imageMap.get(asset.image_data) : null;
               
               if (localPath) {
                 assetTex += `\\begin{center}\n\\includegraphics[max width=0.6\\textwidth]{${localPath}}\n\\end{center}\n`;
               } else if (asset.generated_prompt) {
                 assetTex += `\\begin{center}\n`;
                 assetTex += `  \\fbox{\\parbox{0.8\\textwidth}{\n`;
                 assetTex += `    \\centering \\textit{[ Missing Image Placeholder ]} \\\\\n`;
                 assetTex += `    \\vspace{0.2cm}\n`;
                 assetTex += `    \\textbf{Suggested Diagram Prompt:} ${cleanTextForLatex(asset.generated_prompt)}\n`;
                 assetTex += `  }}\n`;
                 assetTex += `\\end{center}\n`;
               }
            }
            
            if (asset.type === 'plot' && asset.plot_data) {
                const p = asset.plot_data;
                
                let coords = '';
                for(let i = 0; i < p.x_data.length; i++) {
                  coords += `(${p.x_data[i]}, ${p.y_data[i]}) `;
                }

                assetTex += `\\begin{center}\n`;
                assetTex += `\\begin{tikzpicture}\n`;
                assetTex += `\\begin{axis}[\n`;
                assetTex += `    xlabel={${cleanTextForLatex(p.x_label)}},\n`;
                assetTex += `    ylabel={${cleanTextForLatex(p.y_label)}},\n`;
                assetTex += `    width=0.7\\textwidth,\n`;
                assetTex += `    height=7.5cm,\n`;
                assetTex += `    axis lines=left,\n`; 
                assetTex += `    enlargelimits=true,\n`;
                // --- Authentic IB Graph Paper Styling ---
                assetTex += `    grid=both,\n`;
                assetTex += `    minor tick num=4,\n`; // 5 subdivisions between major ticks
                assetTex += `    major grid style={line width=.6pt, draw=black!40},\n`; // Darker major lines
                assetTex += `    minor grid style={line width=.3pt, draw=black!15}\n`;  // Fainter minor lines
                assetTex += `]\n`;
                
                if (p.chart_type === 'scatter') {
                    assetTex += `\\addplot[only marks, mark=*, color=black] coordinates {\n    ${coords}\n};\n`;
                } else if (p.chart_type === 'bar') {
                    assetTex += `\\addplot[ybar, fill=black!20] coordinates {\n    ${coords}\n};\n`;
                } else {
                    assetTex += `\\addplot[color=black, mark=*, thick] coordinates {\n    ${coords}\n};\n`;
                }
                
                assetTex += `\\end{axis}\n`;
                assetTex += `\\end{tikzpicture}\n`;
                assetTex += `\\end{center}\n`;
            }

            if (asset.type === 'table') {
               assetTex += `% Note: Contains a table. Please format manually in LaTeX.\n`;
            }
          });
        }
        return assetTex;
      };

      if (q.Question_Type === 'MCQ') {
        tex += `\\question\n${cleanTextForLatex(q.Stem.text)}\n\n`;
        const assetsTex = renderAssets(q.Stem.assets);
        if (assetsTex) tex += assetsTex + `\n\n`;
        
        tex += `\\begin{choices}\n`;
        q.Options.forEach((opt: any) => {
          tex += `  \\choice ${cleanTextForLatex(opt.text)}\\vspace{0.2cm}\n`;
        });
        tex += `\\end{choices}\n\n`;
      } 
      else if (q.Question_Type === 'Structured_Question') {
        tex += `\\question\n${cleanTextForLatex(q.Stem.text)}\n\n`;
        const stemAssetsTex = renderAssets(q.Stem.assets);
        if (stemAssetsTex) tex += stemAssetsTex + `\n\n`;
        
        tex += `\\begin{parts}\n`;
        q.Parts.forEach((part: any) => {
          const boxHeight = part.marks * 1.5; 
          
          let cTerm = cleanTextForLatex(part.command_term);
          let pText = cleanTextForLatex(part.text);
          
          if (pText.toLowerCase().startsWith(cTerm.toLowerCase())) {
             pText = pText.substring(cTerm.length).trim();
          }
          
          tex += `  \\part[${part.marks}] \\textbf{${cTerm}} ${pText}\n\n`; 
          
          const partAssetsTex = renderAssets(part.assets);
          if (partAssetsTex) tex += partAssetsTex + `\n\n`;
          
          tex += `  \\vspace{0.4cm}\n\n`;
          tex += `  \\noindent\\fbox{%\n`;
          tex += `    \\begin{minipage}{\\dimexpr\\linewidth-2\\fboxsep-2\\fboxrule\\relax}\n`;
          tex += `      \\fillwithdottedlines{${boxHeight}cm}\n`;
          tex += `    \\end{minipage}%\n`;
          tex += `  }\n\n`;
        });
        tex += `\\end{parts}\n\n`;
      }
    }
  });

  tex += `\\end{questions}\n\\end{document}\n`;
  return tex;
};

const cleanTextForLatex = (text: string) => {
  if (!text) return '';
  return text
    .replace(/(?<!\\)%/g, '\\%') 
    .replace(/&/g, '\\&')        
    .replace(/#/g, '\\#');       
};